using System.Collections.Generic;
using System.Linq;
using Godot;
using SpacedOut.Sector;

namespace SpacedOut.LevelGen;

public static class AssetLibrary
{
    private static readonly List<AssetDefinition> Assets = new()
    {
        // ── Asteroid Field ──────────────────────────────────────────
        new AssetDefinition
        {
            Id = "asteroid_large",
            DisplayName = "Großer Asteroid",
            Category = AssetCategory.AsteroidLarge,
            Tags = new[] { "natural", "solid", "landmark" },
            Shape = PlaceholderShape.Sphere,
            Radius = 25f,
            Weight = 1f,
            MinSpacing = 55f,
            AllowedBiomes = new[] { "asteroid_field" },
            IsLandmark = true,
            DebugColor = new Color(0.65f, 0.55f, 0.40f),
            MinScale = 0.8f,
            MaxScale = 1.4f,
            DefaultMapPresence = MapPresence.Point,
        },
        new AssetDefinition
        {
            Id = "asteroid_medium",
            DisplayName = "Mittlerer Asteroid",
            Category = AssetCategory.AsteroidMedium,
            Tags = new[] { "natural", "solid" },
            Shape = PlaceholderShape.Sphere,
            Radius = 12f,
            Weight = 3f,
            MinSpacing = 20f,
            AllowedBiomes = new[] { "asteroid_field" },
            Clusterable = true,
            DebugColor = new Color(0.55f, 0.45f, 0.35f),
            MinScale = 0.7f,
            MaxScale = 1.5f,
            DefaultMapPresence = MapPresence.NearfieldOnly,
        },
        new AssetDefinition
        {
            Id = "asteroid_small",
            DisplayName = "Kleiner Asteroid",
            Category = AssetCategory.AsteroidSmall,
            Tags = new[] { "natural", "scatter" },
            Shape = PlaceholderShape.Sphere,
            Radius = 4f,
            Weight = 5f,
            MinSpacing = 6f,
            AllowedBiomes = new[] { "asteroid_field" },
            Clusterable = true,
            DebugColor = new Color(0.45f, 0.38f, 0.30f),
            MinScale = 0.5f,
            MaxScale = 2.0f,
            DefaultMapPresence = MapPresence.NearfieldOnly,
        },
        new AssetDefinition
        {
            Id = "resource_node",
            DisplayName = "Ressourcen-Knoten",
            Category = AssetCategory.ResourceNode,
            Tags = new[] { "resource", "poi" },
            Shape = PlaceholderShape.Sphere,
            Radius = 3f,
            Weight = 2f,
            MinSpacing = 30f,
            AllowedBiomes = new[] { "asteroid_field" },
            DebugColor = new Color(0.95f, 0.85f, 0.15f),
            MinScale = 0.8f,
            MaxScale = 1.2f,
            DefaultMapPresence = MapPresence.Point,
            MarkerVisual = MarkerVisualType.Glow,
        },

        // ── Wreck Zone ──────────────────────────────────────────────
        new AssetDefinition
        {
            Id = "wreck_main",
            DisplayName = "Hauptwrack",
            Category = AssetCategory.WreckMain,
            Tags = new[] { "wreck", "landmark", "structure" },
            Shape = PlaceholderShape.Box,
            Radius = 35f,
            Weight = 1f,
            MinSpacing = 70f,
            AllowedBiomes = new[] { "wreck_zone" },
            IsLandmark = true,
            DebugColor = new Color(0.50f, 0.25f, 0.20f),
            MinScale = 0.9f,
            MaxScale = 1.3f,
            DefaultMapPresence = MapPresence.Point,
        },
        new AssetDefinition
        {
            Id = "wreck_medium",
            DisplayName = "Mittleres Wrackteil",
            Category = AssetCategory.WreckMedium,
            Tags = new[] { "wreck", "structure" },
            Shape = PlaceholderShape.Box,
            Radius = 14f,
            Weight = 3f,
            MinSpacing = 22f,
            AllowedBiomes = new[] { "wreck_zone" },
            Clusterable = true,
            DebugColor = new Color(0.45f, 0.40f, 0.38f),
            MinScale = 0.6f,
            MaxScale = 1.6f,
            DefaultMapPresence = MapPresence.NearfieldOnly,
        },
        new AssetDefinition
        {
            Id = "debris_cluster",
            DisplayName = "Trümmercluster",
            Category = AssetCategory.DebrisCluster,
            Tags = new[] { "wreck", "scatter", "debris" },
            Shape = PlaceholderShape.Box,
            Radius = 5f,
            Weight = 5f,
            MinSpacing = 7f,
            AllowedBiomes = new[] { "wreck_zone" },
            Clusterable = true,
            DebugColor = new Color(0.35f, 0.33f, 0.30f),
            MinScale = 0.4f,
            MaxScale = 2.2f,
            DefaultMapPresence = MapPresence.NearfieldOnly,
        },
        new AssetDefinition
        {
            Id = "beacon",
            DisplayName = "Signalboje",
            Category = AssetCategory.Beacon,
            Tags = new[] { "marker", "signal" },
            Shape = PlaceholderShape.Capsule,
            Radius = 2f,
            Weight = 2f,
            MinSpacing = 40f,
            AllowedBiomes = new[] { "wreck_zone", "asteroid_field" },
            DebugColor = new Color(0.1f, 0.9f, 0.95f),
            MinScale = 0.9f,
            MaxScale = 1.1f,
            DefaultMapPresence = MapPresence.Point,
            MarkerVisual = MarkerVisualType.Glow,
        },
        new AssetDefinition
        {
            Id = "loot_marker",
            DisplayName = "Loot-Marker",
            Category = AssetCategory.LootMarker,
            Tags = new[] { "loot", "poi" },
            Shape = PlaceholderShape.Capsule,
            Radius = 2.5f,
            Weight = 2f,
            MinSpacing = 35f,
            AllowedBiomes = new[] { "wreck_zone" },
            DebugColor = new Color(0.95f, 0.70f, 0.10f),
            MinScale = 0.8f,
            MaxScale = 1.2f,
            DefaultMapPresence = MapPresence.Point,
            MarkerVisual = MarkerVisualType.Glow,
        },

        // ── Station Periphery ───────────────────────────────────────
        new AssetDefinition
        {
            Id = "station_core",
            DisplayName = "Stationskern",
            Category = AssetCategory.StationCore,
            Tags = new[] { "station", "landmark", "structure" },
            Shape = PlaceholderShape.Cylinder,
            Radius = 40f,
            Weight = 1f,
            MinSpacing = 80f,
            AllowedBiomes = new[] { "station_periphery" },
            IsLandmark = true,
            DebugColor = new Color(0.45f, 0.55f, 0.70f),
            MinScale = 0.9f,
            MaxScale = 1.2f,
            DefaultMapPresence = MapPresence.Point,
        },
        new AssetDefinition
        {
            Id = "station_module",
            DisplayName = "Stationsmodul",
            Category = AssetCategory.StationModule,
            Tags = new[] { "station", "structure", "module" },
            Shape = PlaceholderShape.Cylinder,
            Radius = 12f,
            Weight = 3f,
            MinSpacing = 18f,
            AllowedBiomes = new[] { "station_periphery" },
            Clusterable = true,
            DebugColor = new Color(0.40f, 0.50f, 0.65f),
            MinScale = 0.7f,
            MaxScale = 1.4f,
            DefaultMapPresence = MapPresence.NearfieldOnly,
        },
        new AssetDefinition
        {
            Id = "cargo_cluster",
            DisplayName = "Container-Gruppe",
            Category = AssetCategory.CargoCluster,
            Tags = new[] { "station", "cargo", "scatter" },
            Shape = PlaceholderShape.Box,
            Radius = 6f,
            Weight = 4f,
            MinSpacing = 8f,
            AllowedBiomes = new[] { "station_periphery" },
            Clusterable = true,
            DebugColor = new Color(0.50f, 0.45f, 0.35f),
            MinScale = 0.5f,
            MaxScale = 1.8f,
            DefaultMapPresence = MapPresence.NearfieldOnly,
        },
        new AssetDefinition
        {
            Id = "utility_node",
            DisplayName = "Versorgungsknoten",
            Category = AssetCategory.UtilityNode,
            Tags = new[] { "station", "utility", "poi" },
            Shape = PlaceholderShape.Cylinder,
            Radius = 4f,
            Weight = 2f,
            MinSpacing = 25f,
            AllowedBiomes = new[] { "station_periphery" },
            DebugColor = new Color(0.50f, 0.55f, 0.65f),
            MinScale = 0.8f,
            MaxScale = 1.3f,
            DefaultMapPresence = MapPresence.Point,
            MarkerVisual = MarkerVisualType.Glow,
        },

        // ── Asteroid-field POIs ──────────────────────────────────────
        new AssetDefinition
        {
            Id = "poi_rich_vein",
            DisplayName = "Mineral-Signatur",
            Category = AssetCategory.PoiMarker,
            Tags = new[] { "marker", "poi", "interactable", "poi_blueprint:rich_vein" },
            Shape = PlaceholderShape.Sphere,
            Radius = 4f,
            Weight = 2f,
            MinSpacing = 45f,
            AllowedBiomes = new[] { "asteroid_field" },
            DebugColor = new Color(0.85f, 0.55f, 0.15f),
            MinScale = 1.5f,
            MaxScale = 2.5f,
            DefaultMapPresence = MapPresence.Point,
            MarkerVisual = MarkerVisualType.Glow,
            ScenePaths = new[] { "res://Assets/models/pois/rich_vein_01/rich_vein_01.glb" },
        },
        new AssetDefinition
        {
            Id = "poi_crystal_geode",
            DisplayName = "Kristalline Signatur",
            Category = AssetCategory.PoiMarker,
            Tags = new[] { "marker", "poi", "interactable", "poi_blueprint:crystal_geode" },
            Shape = PlaceholderShape.Sphere,
            Radius = 3.5f,
            Weight = 2f,
            MinSpacing = 45f,
            AllowedBiomes = new[] { "asteroid_field" },
            DebugColor = new Color(0.40f, 0.85f, 0.95f),
            MinScale = 0.85f,
            MaxScale = 1.15f,
            DefaultMapPresence = MapPresence.Point,
            MarkerVisual = MarkerVisualType.Glow,
            ScenePaths = new[] { "res://Assets/models/pois/crystal_geode_01/crystal_geode_01.glb" },
        },
        new AssetDefinition
        {
            Id = "poi_fissure_cavity",
            DisplayName = "Struktur-Anomalie",
            Category = AssetCategory.PoiMarker,
            Tags = new[] { "marker", "poi", "interactable", "poi_blueprint:fissure_cavity" },
            Shape = PlaceholderShape.Sphere,
            Radius = 5f,
            Weight = 1.5f,
            MinSpacing = 50f,
            AllowedBiomes = new[] { "asteroid_field" },
            DebugColor = new Color(0.70f, 0.35f, 0.20f),
            MinScale = 0.9f,
            MaxScale = 1.3f,
            DefaultMapPresence = MapPresence.Point,
            MarkerVisual = MarkerVisualType.Glow,
        },

        // ── Cross-biome wildcard POIs ───────────────────────────────
        new AssetDefinition
        {
            Id = "poi_drifting_pod",
            DisplayName = "Treibendes Objekt",
            Category = AssetCategory.PoiMarker,
            Tags = new[] { "marker", "poi", "interactable", "poi_blueprint:drifting_pod" },
            Shape = PlaceholderShape.Capsule,
            Radius = 2.5f,
            Weight = 2f,
            MinSpacing = 40f,
            AllowedBiomes = new[] { "asteroid_field", "wreck_zone", "station_periphery" },
            DebugColor = new Color(0.90f, 0.70f, 0.10f),
            MinScale = 0.85f,
            MaxScale = 1.15f,
            DefaultMapPresence = MapPresence.Point,
            MarkerVisual = MarkerVisualType.Glow,
        },
        new AssetDefinition
        {
            Id = "poi_anomaly_source",
            DisplayName = "Energiefluktuation",
            Category = AssetCategory.PoiMarker,
            Tags = new[] { "marker", "poi", "interactable", "poi_blueprint:anomaly_source" },
            Shape = PlaceholderShape.Capsule,
            Radius = 3f,
            Weight = 2f,
            MinSpacing = 42f,
            AllowedBiomes = new[] { "asteroid_field", "wreck_zone", "station_periphery" },
            DebugColor = new Color(0.90f, 0.20f, 0.85f),
            MinScale = 0.9f,
            MaxScale = 1.1f,
            DefaultMapPresence = MapPresence.Point,
            MarkerVisual = MarkerVisualType.Glow,
        },
        new AssetDefinition
        {
            Id = "poi_wreck_fragment",
            DisplayName = "Wracksignal",
            Category = AssetCategory.PoiMarker,
            Tags = new[] { "marker", "poi", "interactable", "poi_blueprint:wreck_fragment" },
            Shape = PlaceholderShape.Box,
            Radius = 3f,
            Weight = 2f,
            MinSpacing = 44f,
            AllowedBiomes = new[] { "asteroid_field", "wreck_zone", "station_periphery" },
            DebugColor = new Color(0.50f, 0.45f, 0.40f),
            MinScale = 0.85f,
            MaxScale = 1.2f,
            DefaultMapPresence = MapPresence.Point,
            MarkerVisual = MarkerVisualType.Glow,
        },
        new AssetDefinition
        {
            Id = "encounter_marker",
            DisplayName = "Begegnungssignal",
            Category = AssetCategory.EncounterMarker,
            Tags = new[] { "marker", "encounter", "event" },
            Shape = PlaceholderShape.Capsule,
            Radius = 3f,
            Weight = 1f,
            MinSpacing = 50f,
            AllowedBiomes = new[] { "asteroid_field", "wreck_zone", "station_periphery" },
            DebugColor = new Color(0.95f, 0.30f, 0.15f),
            MinScale = 0.9f,
            MaxScale = 1.1f,
            DefaultMapPresence = MapPresence.Point,
            MarkerVisual = MarkerVisualType.Billboard,
        },
        new AssetDefinition
        {
            Id = "station_dock",
            DisplayName = "Station-Andockmast",
            Category = AssetCategory.Beacon,
            Tags = new[] { "marker", "dock", "station" },
            Shape = PlaceholderShape.Cylinder,
            Radius = 6f,
            Weight = 1f,
            MinSpacing = 20f,
            AllowedBiomes = new[] { "station_periphery" },
            DebugColor = new Color(0.30f, 0.80f, 1.00f),
            MinScale = 1f,
            MaxScale = 1f,
            DefaultMapPresence = MapPresence.Point,
            MarkerVisual = MarkerVisualType.Glow,
        },
        new AssetDefinition
        {
            Id = "exit_marker",
            DisplayName = "Ausgang / Gate",
            Category = AssetCategory.ExitMarker,
            Tags = new[] { "marker", "exit", "navigation" },
            Shape = PlaceholderShape.Capsule,
            Radius = 5f,
            Weight = 1f,
            MinSpacing = 20f,
            AllowedBiomes = new[] { "asteroid_field", "wreck_zone", "station_periphery" },
            DebugColor = new Color(0.15f, 0.95f, 0.30f),
            DefaultMapPresence = MapPresence.Point,
            MarkerVisual = MarkerVisualType.Glow,
        },

        // ── Mission-scoped primary-objective structures ──────────────
        new AssetDefinition
        {
            Id = "station_relay",
            DisplayName = "Navigationsrelais",
            Category = AssetCategory.MissionStructure,
            Tags = new[] { "structure", "mission", "primary_objective", "relay" },
            Shape = PlaceholderShape.Cylinder,
            Radius = 7f,
            Weight = 1f,
            MinSpacing = 40f,
            AllowedBiomes = new[] { "asteroid_field", "wreck_zone", "station_periphery" },
            DebugColor = new Color(0.35f, 0.75f, 0.90f),
            MinScale = 1f,
            MaxScale = 1f,
            DefaultMapPresence = MapPresence.Point,
            ScenePaths = System.Array.Empty<string>(),
            MeshYawRandomize = true,
        },
    };

    public static AssetDefinition? GetById(string id) =>
        Assets.FirstOrDefault(a => a.Id == id);

    public static List<AssetDefinition> GetForBiome(string biome) =>
        Assets.Where(a => a.AllowedBiomes.Contains(biome)).ToList();

    public static List<AssetDefinition> GetLandmarks(string biome) =>
        Assets.Where(a => a.IsLandmark && a.AllowedBiomes.Contains(biome)).ToList();

    public static List<AssetDefinition> GetAll() => Assets;
}
